각종 연습들/ham_temp/cardgame/urls.py
from django.urls import path, include 
from . import views

app_name = "cardgame"

urlpatterns = [
    path("", views.main, name="main"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="log_out"),
    path("signup/", views.sign_up, name="sign_up"),
    path("defend/<int:pk>/", views.defend, name="defend"),
    path("game_detail/<int:pk>",views.game_detail, name="game_detail"),
    path("game_rank/", views.game_rank, name="game_rank"),
    path("game_list/", views.game_list, name="game_list"),
    path('game_delete/<int:pk>', views.game_delete, name='game_delete'),
]

각종 연습들/ham_temp/config/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cardgame.urls')),
    path('accounts/',include('allauth.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

각종 연습들/ham_temp/cardgame/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
  point = models.IntegerField(default=0)

MODE_CHOICE = {('big_num', 'big_num'),('small_num', 'small_num')}
STATUS_CHOICE = {('proceed', 'proceed'),('end', 'end')}
class Game(models.Model):
  attacker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="attacker")
  defender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="defender", null=True)
  attack_card = models.IntegerField(null=True)
  defend_card = models.IntegerField(null=True, blank=True)
  game_mode = models.CharField(max_length=20, choices=MODE_CHOICE)
  game_status = models.CharField(max_length=20, choices=STATUS_CHOICE)
  victory_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

각종 연습들/ham_temp/cardgame/forms.py
from django import forms
from .models import User, Game
from django.contrib.auth.forms import UserCreationForm
import random

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        try:
            user = User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                raise forms.ValidationError("비밀번호가 일치하지 않습니다!")
        except User.DoesNotExist:
            raise forms.ValidationError("해당 사용자가 존재하지 않습니다!")

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

def MakeRandomCard():
    choice_list=[('','----')]
    num_list = random.sample([1,2,3,4,5,6,7,8,9,10], 5)
    for num in num_list:
        temp = []
        temp.append(num)
        temp.append(num)
        temp = tuple(temp)
        choice_list.append(temp)
    choice_list=tuple(choice_list)
    return choice_list

class AttackForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AttackForm, self).__init__(*args, **kwargs)
        self.fields['attack_card'] = forms.ChoiceField(choices=MakeRandomCard(), label="내가 고른 카드")
    class Meta:
        model = Game
        fields = ['attack_card', 'defender']

class DefendForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DefendForm, self).__init__(*args, **kwargs)
        self.fields['defend_card'] = forms.ChoiceField(choices=MakeRandomCard(), label="내가 고른 카드")
    class Meta:
        model = Game
        fields = ['defend_card']

각종 연습들/ham_temp/cardgame/views.py
from django.shortcuts import redirect, render
from django.urls import is_valid_path
from django.views import View
from . import forms
from .models import User, Game
from django.contrib.auth import authenticate, login, logout
import random

class LoginView(View):
    def get(self, request):
        form = forms.LoginForm()
        context = {
            "form" : form
        }
        return render(request, "cardgame/login.html", context)

    def post(self, request):
        form = forms.LoginForm(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username = username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect("cardgame:main")

        context = {
            "form" : form
        }
        return render(request, "cardgame/login.html", context)
# Create your views here.
def main (request):
    return render(request, "cardgame/main.html")

def sign_up(request):
    if request.method == "POST":
        form = forms.SignupForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("cardgame:main")

        return render(request, "cardgame/sign_up.html", {'form':form})

    else:
        form = forms.SignupForm()
        context = {
            "form" : form
        }
        return render(request, "cardgame/sign_up.html", context)

def log_out(request):
    logout(request)
    return redirect("cardgame:main")

def game_rank(request):
    users = User.objects.all().order_by('-point')
    
    context = {
        "users" : users
    }
    return render(request, 'cardgame/game_rank.html', context=context)
    
def defend(request, pk):
    game = Game.objects.get(pk = pk) 
    
    if request.method == "POST":
        form = forms.DefendForm(request.POST, instance=game)
        
        if form.is_valid():
            if game.attack_card == game.defend_card : #공격카드와 방어카드가 같은 수라면
                game.tie_flag = 1 #무승부 표시
            else :
                if game.game_mode == 'big_num' : #큰 수가 이기는 게임이라면
                    if game.attack_card > game.defend_card : #attacker가 이겼을 경우
                        game.victory_user = game.attacker
                        game.attacker.point += game.attack_card
                        game.defender.point -= game.defend_card
                    else : #defender가 이겼을 경우
                        game.victory_user = game.defender
                        game.attacker.point -= game.attack_card
                        game.defender.point += game.defend_card
                else : #작은 수가 이기는 게임이라면
                    if game.attack_card < game.defend_card : #attacker가 이겼을 경우
                        game.victory_user = game.attacker
                        game.attacker.point += game.attack_card
                        game.defender.point -= game.defend_card
                    else : #defender가 이겼을 경우
                        game.victory_user = game.defender
                        game.attacker.point -= game.attack_card
                        game.defender.point += game.defend_card
            game.game_status = 'end' #game_status를 'end'로 변경
            game.save() #game의 변경된 status 저장
            game.attacker.save() #attacker의 변경된 point 저장
            game.defender.save() #defender의 변경된 point 저장
            form.save()
            return redirect('/')
        else :
            return redirect('/')
    else :
        form = forms.DefendForm()
        context = {
            'form' : form,
            'game' : game
        }
        return render(request, 'cardgame/defend.html', context=context)

def game_detail(request, pk) :
    game = Game.objects.get(pk = pk)
    request_user = request.user
    
    context = {
        'game' : game,
        'request_user' : request_user
    }
    return render(request, 'cardgame/game_detail.html', context=context)

def game_list(request):
    game = Game.objects.all() 
    users = User.objects.all()
    attack_game = game.filter(attacker=request.user) 
    defend_game = game.filter(defender = request.user)

    games = attack_game.union(defend_game) #전체 게임
    status_proceed = game.filter(game_status = 'proceed') #진행 중인 상태인 게임
    stauts_end = game.filter(game_status = 'end') #완료된 상태인 게임
    context = {
        'status_proceed' : status_proceed,
        'stauts_end' : stauts_end,
        'games' : games,
        'current_user': request.user,
        'users':users
    }
    return render(request, 'cardgame/game_list.html', context=context)

def game_delete(request, pk):
    game = Game.objects.get(id=pk)
    game.delete()
    return redirect("cardgame:game_list")

각종 연습들/ham_temp/cardgame/templates/cardgame/defend.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/defend.css' %}" />
    <title>4조</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    <nav class="navbar">
      <ul class="navbar-list">
        <li class="navbar-title"><a href="/">PIROGRAM CARDGAME</a></li>
        <li><a href="">게임하기</a></li>
        <li><a href="{% url 'cardgame:game_rank' %}">랭킹보기</a></li>
        <li><a href="{% url 'cardgame:log_out' %}">로그아웃</a></li>
      </ul>
    </nav>
    <div class="main">
      <div class="vs">
        <p id="defeat-text">세기의 격돌...</p>
        <p id="attackerVSdefender">{{game.attacker}} VS {{game.defender}}</p>
      </div>
      <div>
        <p id="defend-text">{{game.attacker}}에게 반격하세요!</p>
      </div>
      <form action="/defend/{{game.id}}/" method="POST">
        {% csrf_token %}
        <table>
          {{form.as_p}}
        </table>
        <input type="submit" value="반격하기!" />
      </form>
    </div>
    {% else %}
    <script type="text/javascript">
      alert('먼저 로그인을 해주세요🥺')
      window.location.href = '{% url 'cardgame:login' %}';
    </script>
    {% endif %}
  </body>
</html>

각종 연습들/ham_temp/cardgame/templates/cardgame/game_detail.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/game_detail.css' %}" />
    <title>4조</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    <nav class="navbar">
      <ul class="navbar-list">
        <li class="navbar-title"><a href="/">PIROGRAM CARDGAME</a></li>
        <li><a href="">게임하기</a></li>
        <li><a href="{% url 'cardgame:game_rank' %}">랭킹보기</a></li>
        <li><a href="{% url 'cardgame:log_out' %}">로그아웃</a></li>
      </ul>
    </nav>
    <div class="main">
      <p>{{game.id}}번째 대결 - {{game.attacker}} VS {{game.defender}}</p>
      {% if game.game_status == 'proceed' %}<!--게임 상태가 proceed라면-->
      {% if game.attacker == request_user %}<!--공격자가 자신이라면-->
      <form action="/game_delete/{{game.id}}" method="post">
        {% csrf_token%}
        <button class="btn">게임 취소</button>
      </form>
      {% else %}<!--공격자가 상대방이라면-->
      <a href="/defend/{{game.id}}">반격하기</a>
      {% endif %} {% else %}<!--게임 상태가 end라면-->
      {% if game.game_mode == 'big_num' %}
      <p>숫자가 더 큰 사람이 대결에서 이깁니다.</p>
      {% else %}
      <p>숫자가 더 작은 사람이 대결에서 이깁니다.</p>
      {% endif %}
      <p>{{game.attacker}}님이 낸 카드 : {{game.attack_card}}</p>
      <p>{{game.defender}}(나)님이 낸 카드 : {{game.defend_card}}</p>
      {% if game.attack_card==game.defend_card %}<!--무승부라면-->
      <p>결과 : 무승부</p>
      <p>점수 : 변동없음</p>
      {% else %}<!--무승부가 아니라면-->
      {% if game.victory_user == request_user%}<!--이긴사람이 자신이라면-->
      <p>결과 : 승리</p>
      {% if request_user == game.attacker %}
      <p>점수 : +{{ game.attack_card }}</p>
      {% else %}
      <p>점수 : +{{ game.defend_card }}</p>
      {% endif %} {% else %}<!--이긴사람이 상대방이라면-->
      <p>결과 : 패배</p>
      {% if request_user == game.attacker %}
      <p>점수 : -{{ game.attack_card }}</p>
      {% else %}
      <p>점수 : -{{ game.defend_card }}</p>
      {% endif %} {% endif %} {% endif %} {% endif %}
    {% else %}
    <script type="text/javascript">
      alert('먼저 로그인을 해주세요🥺')
      window.location.href = "{% url 'cardgame:login' %}";
    </script>
    {% endif %}
  </body>
</html>

각종 연습들/ham_temp/cardgame/templates/cardgame/game_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>4조</title>
  </head>
  <body>
    <li><a href="/">PIROGRAM CARDGAME(홈으로 이동)</a></li>
    {% block content %} {% if user.is_authenticated %}
    <p>현재 플레이어 : {{user.username}}</p>
    {% for game in games reversed %}
    <div>{{game.attacker.username}} VS {{game.defender.username}}</div>
    <div>
      {% if game in status_proceed %} {% if game.attacker.username ==
      current_user.username %}
      <p>
        진행중...<a href="{% url 'cardgame:game_delete' pk=game.id%}"
          >게임 취소</a
        >
      </p>
      {% elif game.defender.username == current_user.username %}
      <a href="{% url 'cardgame:defend' pk=game.id%}">반격하기</a>
      {% endif %}
      <a href="">게임 정보</a>
      {% endif %} {% if game in status_end %} {% if game.attack_card ==
      game.defend_card %}
      <p>무승부</p>
      {% elif game.victory_user.username == current_user.username %}
      <p>결과 : 승리</p>
      {% elif game.victory_user.username != current_user.username %}
      <p>결과 : 패배</p>
      {% endif %}
      <a href="">게임 정보</a>
      {% endif %}
    </div>
    {% endfor %} {% else %}
    <script type="text/javascript">
      alert("먼저 로그인을 해주세요🥺");
      window.location.href = "{% url 'cardgame:login' %}";
    </script>
    {% endif %} {% endblock content %}
  </body>
</html>

각종 연습들/ham_temp/cardgame/templates/cardgame/game_rank.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Prompt:wght@500&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/game_rank.css' %}" />
    <title>4조</title>
  </head>
  <body>
    <nav class="navbar">
      <div class="navbar-title"><a href="/">PIROGRAM CARDGAME</a></div>
      <ul class="navbar-list">
        <li><a href="">게임하기</a></li>
        <li><a href="{% url 'cardgame:game_rank' %}">랭킹보기</a></li>
        <li><a href="{% url 'cardgame:log_out' %}">로그아웃</a></li>
      </ul>
    </nav>
    <div class="content">
      <div class="content-box">
        <div class="box-title">PIRO 명예의 전당</div>
        {% for user in users %} {% if forloop.first %}
        <div class="first-content">
          <div>{{ forloop.counter }}등</div>
          <div>{{ user.username }}님!</div>
          <div>총점수 : {{ user.point }}점</div>
        </div>
        {% else %}
        <div class="box-content">
          <div>{{ forloop.counter }}등</div>
          <div>{{ user.username }}님!</div>
          <div>총점수 : {{ user.point }}점</div>
        </div>
        {% endif %} {% endfor %}
        <a id="list_btn" href="{% url 'cardgame:game_list' %}">전적보기</a>
      </div>
    </div>
    <footer class="footer">
      <div class="footer-title">피로그래밍 17기 화이팅 ~ ~ ₩ 최강4조</div>
      <div class="footer-content">
        뭐라쓰지 뭐라쓰지 뭐라쓰지 | 조하연 심은서 이현영 장명지 조석현
      </div>
    </footer>
  </body>
</html>

각종 연습들/ham_temp/cardgame/templates/cardgame/login.html
{% extends 'cardgame/main.html' %} {% load static %} {% load socialaccount %} {%
providers_media_js %} {% block content %}
<form method="POST" action="">
  {% csrf_token %} {{ form }}
  <button>로그인</button>
</form>
<a href="{% provider_login_url 'google' %}">구글 로그인</a><br />
<a href="{% provider_login_url 'naver' %}">네이버 로그인</a>
<li><a href="{% url 'cardgame:sign_up' %}">회원가입</a></li>

{% endblock content %}

각종 연습들/ham_temp/cardgame/templates/cardgame/main.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Prompt:wght@500&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>4조</title>
  </head>
  <body>
    {% block content %} {% if user.is_authenticated %}
    <nav class="navbar">
      <div class="navbar-title"><a href="/">PIROGRAM CARDGAME</a></div>
      <ul class="navbar-list">
        <li><a href="">게임하기</a></li>
        <li><a href="{% url 'cardgame:game_rank' %}">랭킹보기</a></li>
        <li><a href="{% url 'account_logout' %}">로그아웃</a></li>
      </ul>
    </nav>
    <div class="content">
      <div class="content-title">
        전 세계 피로그래머와 <br />
        한 판 승부 숫자카드게임
      </div>
      <div class="content-login">{{user.username}} 님이 로그인 중</div>
      <div class="content-game_btn"><a href="">게임하기</a></div>
      <div class="content-list_btn">
        <a href="{% url 'cardgame:game_list' %}">전적보기</a>
      </div>
    </div>
    {% else %}
    <nav class="navbar">
      <div class="navbar-title"><a href="/">PIROGRAM CARDGAME</a></div>
      <ul class="navbar-list">
        <li><a href="{% url 'cardgame:login' %}">로그인</a></li>
      </ul>
    </nav>
    <div class="content">
      <div class="content-title">
        전 세계 피로그래머와 <br />
        한 판 승부 숫자카드게임
      </div>
      <div class="content-game_btn">
        <a href="{% url 'cardgame:login' %}">게임하기</a>
      </div>
    </div>
    {% endif %} {% endblock content %}

    <footer class="footer">
      <div class="footer-title">피로그래밍 17기 화이팅 ~ ~ ₩ 최강4조</div>
      <div class="footer-content">
        뭐라쓰지 뭐라쓰지 뭐라쓰지 | 조하연 심은서 이현영 장명지 조석현
      </div>
    </footer>
  </body>
</html>

각종 연습들/ham_temp/cardgame/templates/cardgame/sign_up.html
{% extends 'cardgame/main.html' %} {% block content %}
<form method="POST" action="">
  {% csrf_token %} {% include "cardgame/signup_errors.html" %}
  <label for="username">사용자 이름</label>
  <input
    type="text"
    class="form-control"
    name="username"
    id="username"
    value="{{ form.username.value|default_if_none:'' }}"
  />
  <label for="password1">비밀번호</label>
  <input
    type="password"
    class="form-control"
    name="password1"
    id="password1"
    value="{{ form.password1.value|default_if_none:'' }}"
  />
  <label for="password2">비밀번호 확인</label>
  <input
    type="password"
    class="form-control"
    name="password2"
    id="password2"
    value="{{ form.password2.value|default_if_none:'' }}"
  />
  <input type="submit" value="회원가입" />
</form>
<li><a href="{% url 'cardgame:login' %}">로그인</a></li>

{% endblock content %}

각종 연습들/ham_temp/cardgame/templates/cardgame/signup_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
  <!-- 필드 오류 -->
  {% if field.errors %}
  <div>
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
  </div>
  {% endif %} {% endfor %}
  <!-- 넌필드 오류 -->
  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}