장고 django 실습/User_Model_Custom/userproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls"))
]

장고 django 실습/User_Model_Custom/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.main, name="main"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="log_out"),
    path("sign/", views.sign_up, name="sign_up"),
]

장고 django 실습/User_Model_Custom/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    GENDER_CHOCIE = (
        ("FEMALE", "female"),
        ("MALE", "male"),
        ("ETC", "etc"),
    )
    desc = models.CharField(max_length=255, null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOCIE)
    birthday = models.DateField(null=True)

장고 django 실습/User_Model_Custom/users/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    def clean(self):
        input_email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        
        try:
            user = User.objects.get(username=input_email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                raise forms.ValidationError("password is wrong")
            
        except User.DoesNotExist:
            raise forms.ValidationError("There is no user")
        
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

장고 django 실습/User_Model_Custom/users/views.py
from django.shortcuts import redirect, render
from django.views import View
from . import forms
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def main(request):
    return render(request, "users/main.html")

class LoginView(View):
    def get(self, request):
        form = forms.LoginForm()
        ctx = {"form": form}
        return render(request, "users/login.html", ctx)
    
    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return render(request, "users/success.html")
        
        return render(request, "users/login.html", {"form": form})

def log_out(request):
    logout(request)
    return redirect("users:main")

def sign_up(request):
    if request.method == "POST":
        form = forms.SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, "users/success.html")
        return redirect("users:sign_up")
    else:
        form = forms.SignupForm()
        return render(request, "users/signup.html", {"form":form})

장고 django 실습/User_Model_Custom/templates/users/login.html
{% extends 'users/main.html' %} {% block content %}
<form method="POST" action="">
  {% csrf_token %} {{form}}
  <button>Login</button>
</form>
{% endblock content %}

장고 django 실습/User_Model_Custom/templates/users/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    <li><a href="{% url 'users:log_out' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'users:login' %}">Login</a></li>
    <li><a href="{% url 'users:sign_up' %}">Signup</a></li>
    {% endif %} {% block content %} {% endblock content %}
  </body>
</html>

장고 django 실습/User_Model_Custom/templates/users/signup.html
{% extends 'users/main.html' %} {% block content %}
<form method="POST" action="">
  {% csrf_token %} {{ form }}
  <input type="submit" value="SignUp" />
</form>
{% endblock content %}

장고 django 실습/User_Model_Custom/templates/users/success.html
{% extends 'users/main.html' %} {% block content %} success! {% endblock %}